web:
  container_name: 'whaticket-serv'
  image: nginx
  ports:
          - 80:80
          - 8000:8000  
          - 443:443
  volumes:
      - ./nginx/whaticket.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/cert/:/etc/nginx/cert/

  command: [nginx-debug, '-g', 'daemon off;']
