version: '3.8'

services: 
  mysqldb:
    image: mysql
    container_name: whaticket-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
    networks:
      - localwhat
  back:      
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: wha-back
    container_name: whaticket-back
    # command: bash -c "
    #       npx sequelize db:migrate"
    restart: always
    environment:
      - APPLICATION_URL=mysqldb
    ports:
      - $PORT:$PORT
    volumes:
      - ./backend/.env:/usr/src/app/backend/.env
    depends_on:
      - mysqldb
    networks:
      - localwhat
  front:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: wha-front
    stdin_open: true
    container_name: whaticket-front
    ports:
      - 3333:5000
    volumes:
      - ./frontend/.env:/usr/src/app/frontend/.env
    networks:
      - localwhat
  web:
    container_name: 'whaticket-serv'
    image: nginx
    networks:
      - localwhat
    ports:
      - 80:80
      - 8000:8000
      - 443:443
    volumes:
      - ./nginx/whaticket.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/cert/:/etc/nginx/cert/
    command: [nginx-debug, '-g', 'daemon off;']
volumes: 
  db-config:
  db-data:
networks:
  localwhat:
